### ISSUE TITLE
Add this repo to chriskempson/base16

### ISSUE THREAD

**Issue by Nielius** [tinted-theming/tinted-tmux#4]
Thanks for the config in this repo! I just used it and can finally see all the text on the status bar again.

Is there any reason this repo is not listed on https://github.com/chriskempson/base16 yet?  Listing it would make it easier to find. I'm happy to raise the PR for you if you'd like.

**Comment by mattdavis90** [comment]
Hi, thanks for using the scheme. I'm glad it is working for you.

There's no reason it isn't in the Readme. Originally I added it to the [list](https://github.com/chriskempson/base16-templates-source/blob/master/list.yaml#L63) but not the Readme because I want sure the etiquette on adding it there. Someone did open a PR in 2019 but it was closed without being merged, [here](https://github.com/chriskempson/base16/pull/183). You're more than welcome to open a PR on my behalf though and if you link back to her then I guess the maintainers can see that I endorse it. Thanks

**Comment by JamyGolden** [comment]
@Nielius the community wants to move the base16* projects forward, but the initial creator of base16 has acted in a way that shows they aren't interested: https://github.com/tinted-theming/home/issues/51, so the new home, which this project is listed on, is https://github.com/tinted-theming/home
